/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/flask.glb 
Author: BerserkerBroon (https://sketchfab.com/BerserkerBroon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lowpoly-flask-dcf232cf9e964c478a1b2d59b8097510
Title: LowPoly - Flask
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Flask(props) {
  const { nodes, materials } = useGLTF("/flask.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cylinder_0.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials.Cork} />
        {/* <mesh
          geometry={nodes.Cylinder_2.geometry}
          material={materials.Liquid}
        /> */}
        <mesh
          geometry={nodes.Cylinder_2.geometry}
          castShadow={false}
          receiveShadow={false}
        >
          <meshPhysicalMaterial
            color="#22d3ee"
            transmission={0.4}
            opacity={0.9}
            transparent
            roughness={0.1}
            thickness={1}
            emissive="#0891b2"
            emissiveIntensity={0.8}
          />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/flask.glb");
