/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/laptop.glb 
Author: senthil123 (https://sketchfab.com/senthil123)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-426afac17c664f1a9e3224394024fb7e
Title: Laptop
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Laptop(props) {
  const { nodes, materials } = useGLTF("/laptop.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.589}>
        <mesh
          geometry={nodes.Laptop_Laptop1_0.geometry}
          material={materials.Laptop1}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/laptop.glb");
